### ISSUE TITLE
Crashes and reboots when trying to download FreeSound sound by ID

### ISSUE THREAD

**Issue by guytaylor** [ctag-fh-kiel/ctag-straempler#16]
Repro steps:
1. Select Sample
2. Select ID
3. Enter a valid FreeSound ID e.g. 123

Unit crashes and reboots    (My token replaced with xxxxxx)
A few observations:
* the port appears incorrect, as it should be 443
* Assuming this URL is to retrieve metadata should it include the 'format' parameter eg. 'https://freesound.org/apiv2/sounds/123/?format=json&token=xxxxxx'

Logs:

W (92316) id: 123
I (93116) HTTP_REQ: Following: https://freesound.org:80/apiv2/sounds/123/?token=xxxxxx
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4018e9b7  PS      : 0x00060a30  A0      : 0x80175d84  A1      : 0x3ffecbe0
A2      : 0x00000000  A3      : 0xffffffff  A4      : 0x00000001  A5      : 0x3ffecab0
A6      : 0x00000087  A7      : 0x3ffecab0  A8      : 0x3ffae940  A9      : 0x00000087
A10     : 0x00000000  A11     : 0x3ffecaf4  A12     : 0x3ffecad4  A13     : 0x00000000
A14     : 0x0000005c  A15     : 0xff000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000018  LBEG    : 0x4008b535  LEND    : 0x4008b545  LCOUNT  : 0xffffffe8

ELF file SHA256: 4a55c6babb07d1bd75da8f939e30e0b3cd5f2871fb7e3cee016c99f74212d90c

Backtrace: 0x4018e9b7:0x3ffecbe0 0x40175d81:0x3ffecc00 0x4016b286:0x3ffecc20 0x4016bff6:0x3ffecc40 0x40127066:0x3ffecd00

Rebooting...

**Comment by ctag-fh-kiel** [comment]
Unfortunately, I don't have an old ESP IDF up an running to fix the
firmware, this seems a problem with current freesound web services. Best
would be to port Strämpler to the latest release IDF, would you be willing
to help?

**Comment by ctag-fh-kiel** [comment]
The freesound API has completely moved to https, thus that part in Strämpler firmware needs to be adapted. I have been able to bring the fw to IDF 4.1 as a starting point in this branch:
migrate_idf_4.x

**Comment by guytaylor** [comment]
Let me give setting the dev env up a crack. :)

**Comment by guytaylor** [comment]
Hi Robert,
How's it going? :)
I am happy to give it a go. I have a lot of programming experience, mainly
in C# but some C++. I have not used ESP-IDF before but have done lots of
Arduino stuff, so could I trouble you for a couple of pointers to get me
started?
Hopefully just a couple of basic things! please bear with me :)

So I'm following this guide (
https://github.com/ctag-fh-kiel/ctag-straempler/wiki/GettingStarted), and i
am working on a Windows 10 machine.
I've installed the standard ESP-IDF and that is working fine.

I've done "Installing / replacing standard ESP-IDF"
- But when I run ESP-IDF 4.3 PowerShell I get the following errors. Is this
ok?
[image: image.png]

*- GCC version*
when I type gcc --version. I get this:
gcc.exe (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0

does that mean I am ok, and don't need to install GCC?

*-- Setup ULT toolchain*
I was reading the docs and it states: "If you have already set up ESP-IDF
with CMake build system according to the Getting Started Guide
<https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html>,
then the ULP toolchain will already be installed."
I used the windows installer, so I assume that I don't need to install this
explicitly?

So... if all the above is good, I should be set up!

Next, I did:
git clone --recursive https://github.com/ctag-fh-kiel/ctag-straempler.git

and then I tried : *make menuconfig*
but got the following error:
*C:/Users/guy/Desktop/esp-idf//make/project.mk:114 <http://project.mk:114>:
*** IDF_PATH cannot contain colons. If overriding IDF_PATH on Windows, use
MSYS Unix-style /c/dir instead of C:/dir.  Stop.*

If you notice above:
[image: image.png]
Looks like my environment path is being setup incorrectly
I even tried setting it explicitly in windows:
[image: image.png]
But no luck, I still see the same 'Setting IDF_PATH: C:/users...' when
I run powershell

Do you know how I can fix that?

I can see your new branch, so once I have the above working, I shall try
and compile that.
What state is that in? As in, if I just compile and deploy it, should the
strampler work as it does now?

Thanks!
Guy

**Comment by guytaylor** [comment]
Hey Robert, I sent you an email

**Comment by ctag-fh-kiel** [comment]
Hi Guy, thanks for your help. I have been able to port Strämpler to esp idf 4.1, there were a number of significant changes.
Please check the binaries in the dev branch (folder bin/) and flash them with the flash.sh script. 
Downloading from freesound should work with them. 
I will cut a new public release once you confirm it works.
Strampler has now a Github action, which allows to compile the firmware in the cloud. 
I will eventually write a documentation for it. 
Using a docker image is the easiest way for you to get your own dev environment up and running.
You can check the action in the .github/workflows folder.
If you enable Github actions in your Github account, your can build firmwares automatically every time you push into the dev branch of your fork. Binaries are then available as draft binary under your fork's releases.

Let me know if the firmware works now.

**Comment by guytaylor** [comment]
I tried to get a sample by ID from FreeSound (93727).

It didn't restart but it just sat there. I left it for about 10 minutes (it's a 900k sample, so I assume it should have downloaded in that time)
The screen had to progress indicator but the clock did continue to run.
This is what was in the logs:

I (5416) MDNS: Initialize service...
I (5416) REST-API: Starting server on port: '80', prio 5
I (5416) REST-API: Registering URI handlers
W (73386) id: 93727

**Comment by ctag-fh-kiel** [comment]
Strange, it works for me, this is my log. Make sure your wifi is working
well. You can check from your laptop to access the freesound URLs directly
and see if it generally should work in your network.
https://freesound.org/apiv2/sounds/93727/?token=dKJhasdkjhasdASKdjh (use
your API token)
https://freesound.org/data/previews/93/93727_377011-hq.mp3

On the SD card you have to give the correct freesound token.
I have published this as a pre-release here:
https://github.com/ctag-fh-kiel/ctag-straempler/releases/tag/0.9-pre maybe
re-flash to this binary


I (11851) REST-API: Starting server on port: '80', prio 5

I (11851) REST-API: Registering URI handlers

W (47591) id: 93727

I (47591) fsnd:
https://freesound.org/apiv2/sounds/93727/?token=dKJhasdkjhasdASKdjh

I (49361) FSND: mp3 file info {"id":93727,"url":"
https://freesound.org/people/zgump/sounds/93727/","name":"TR LOOP
0416.wav","tags":["goa","goa-trance","goatrance","loop","psy","psy-trance","psytrance","trance"],"description":"loop
psy psy-trance psytrance trance goatrance goa-trance
goa","geotag":null,"created":"2010-03-31T17:57:23","license":"
http://creativecommons.org/publicdomain/zero/1.0/
","type":"wav","channels":2,"filesize":908150,"bitrate":1378,"bitdepth":16,"duration":5.14732,"samplerate":44100.0,"username":"zgump","pack":"
https://freesound.org/apiv2/packs/6038/","pack_name":null,"download":"
https://freesound.org/apiv2/sounds/93727/download/","bookmark":"
https://freesound.org/apiv2/sounds/93727/bookmark/
","previews":{"preview-lq-ogg":"
https://freesound.org/data/previews/93/93727_377011-lq.ogg
","preview-lq-mp3":"
https://freesound.org/data/previews/93/93727_377011-lq.mp3
","preview-hq-ogg":"
https://freesound.org/data/previews/93/93727_377011-hq.ogg
","preview-hq-mp3":"
https://freesound.org/data/previews/93/93727_377011-hq.mp3
"},"images":{"spectral_m":"
https://freesound.org/data/displays/93/93727_377011_spec_M.jpg
","spectral_l":"
https://freesound.org/data/displays/93/93727_377011_spec_L.jpg
","spectral_bw_l":"
https://freesound.org/data/displays/93/93727_377011_spec_bw_L.jpg
","waveform_bw_m":"
https://freesound.org/data/displays/93/93727_377011_wave_bw_M.png
","waveform_bw_l":"
https://freesound.org/data/displays/93/93727_377011_wave_bw_L.png
","waveform_l":"
https://freesound.org/data/displays/93/93727_377011_wave_L.png
","waveform_m":"
https://freesound.org/data/displays/93/93727_377011_wave_M.png
","spectral_bw_m":"
https://freesound.org/data/displays/93/93727_377011_spec_bw_M.jpg
"},"num_downloads":169,"avg_rating":4.6,"num_ratings":5,"rate":"
https://freesound.org/apiv2/sounds/93727/rate/","comments":"
https://freesound.org/apiv2/sounds/93727/comments/
","num_comments":0,"comment":"
https://freesound.org/apiv2/sounds/93727/comment/","similar_sounds":"
https://freesound.org/apiv2/sounds/93727/similar/","analysis":"No
descriptors specified. You should indicate which descriptors you want with
the 'descriptors' request parameter.","analysis_frames":"
https://freesound.org/data/analysis/93/93727_377011_frames.json
","analysis_stats":"https://freesound.org/apiv2/sounds/93727/analysis/","ac_analysis":{"ac_tempo_confidence":0.9896296262741089,"ac_note_confidence":0.8253257870674133,"ac_depth":18.11034269674787,"ac_note_midi":52,"ac_temporal_centroid":0.4961334764957428,"ac_warmth":38.53786932424461,"ac_loop":true,"ac_hardness":57.687418322872134,"ac_loudness":-20.077274322509766,"ac_reverb":false,"ac_roughness":47.08115554605569,"ac_log_attack_time":-0.05868467688560486,"ac_boominess":15.989786649292943,"ac_note_frequency":164.5169219970703,"ac_tempo":70,"ac_brightness":58.45493938743502,"ac_sharpness":41.63989618168988,"ac_tonality_confidence":0.8204907774925232,"ac_dynamic_range":0.7360343933105469,"ac_note_name":"E3","ac_tonality":"E
minor","ac_single_event":false}}

I (49621) ID: mp3 URL is:
https://freesound.org/data/previews/93/93727_377011-hq.mp3, fname:
/pool/93727.mp3

I (53431) FREESOUND: Completed

I (53431) Menu: Got Freesound MP3 complete!

I (85491) MP3: Decode MP3

I (85511) MP3: Infile /pool/93727.MP3, outfile /raw/93727.RAW

I (85511) MP3: nChannels 2

I (85511) MP3: Decoder task, working with: fin /pool/93727.MP3, fout
/raw/93727.RAW

I (85521) MP3: Size of mp3 file to be decoded 124425

I (85531) MP3: Decoder instantiated

I (85541) MP3: MP3 Error 0

I (85541) MP3: FrameInfo: 44100

**Comment by guytaylor** [comment]
I tried the new binary and it worked :)
Thanks
