### ISSUE TITLE
cv6 and cv7 don't work in the CV Matrix

### ISSUE THREAD

**Issue by guytaylor** [ctag-fh-kiel/ctag-straempler#17]
I was in the process of testing that all my CV input were working correctly.

So I tried mapping the various CV input to a property e.g. V0 Volume. (I also tried a few others)

CV3 4 altered the volume from medium loudness to full loudness (is this correct?)
CV5 and CV8 varied the volume correctly from silence to full volume
CV6 and CV 7 made to difference at all to volume

I checked the voltages on the input pins to the ADC and they all varied from 0v->3.3V

So, I assume it's a software issue?

I checked the logs but nothing seems to be logged around those operations
Thanks

**Comment by ctag-fh-kiel** [comment]
Hi Guy,

CV1+2 are only for pitch CV 1V/Octave ranging from -1.5 ... 5.5 V
CV3+4 are bi-polar CV ranging from -5...5V (so if you want e.g. 0 volume,
you have to apply -5V to these ins)
CV5-8 are uni-polar CV ranging from 0...5V, their value is offset by
whatever you adjust on pots 5-8 (i.e. if you want to use external CV to
modulate, you have to move the pot position all left not to offset the
external CV)

I have checked with the current firmware you have, everything works as
expected.

**Comment by guytaylor** [comment]
Hi,
I've worked out the problem (Maybe this is just on the Antrumbra boards)
CH6 and CH7 are reversed.  CV7 Cv source is actual hardware in CV6  and vice versa

**Comment by ctag-fh-kiel** [comment]
Seems a wiring issue on the Antumbra PCBs... You could fix it in the
firmware and flash your custom fw...

**Comment by guytaylor** [comment]
happy to try! 
I had a couple of issues getting my dev env working. Did you get my email with a few questions in there? :)

**Comment by ctag-fh-kiel** [comment]
Yup, I'd recommend to use a Docker image (updated the readme recently):
https://github.com/ctag-fh-kiel/ctag-straempler#build-instructions

Editing this file should help (lines 66ff):
https://github.com/ctag-fh-kiel/ctag-straempler/blob/master/components/drivers/spi_per.c

Good luck :)

**Comment by guytaylor** [comment]
I just swapped the pins in hardware for an immediate fix!

Great, thanks. I'll give it a go. I am keen to build the firmware

**Comment by ctag-fh-kiel** [comment]
Awesome :)
