### ISSUE TITLE
 The module is rebooting

### ISSUE THREAD

**Issue by Synthwall** [ctag-fh-kiel/ctag-straempler#19]
When accessing almost any menu item, the module is loaded. Upon entering the SLOT menu, the module will immediately reboot. The presence of an SD card in the slot does not affect this in any way. I think that the problem is in the firmware, maybe I did something wrong. I tried to remove all microcircuits to eliminate their influence, but it did not help. WiFi my phone does not detect from the module, I can not change the wifi settings either. Flashed via USB port, Windows 10. Software -ESP32 Download-Tool v3.6.4
![image001 (1)](https://user-images.githubusercontent.com/102356241/160098239-791dc56f-7714-4ca3-9141-4a2382ab73c5.png)

**Comment by ctag-fh-kiel** [comment]
Are you using a freshly FAT32 formated SD card? Try a few different ones, some cards don't seem to work reliably with the ESP32...

**Comment by Synthwall** [comment]
Presence or absence
SD card does not affect this, I tried to change. I don't see the CLK signal on the SD card, the ESP32 doesn't seem to be accessing it at all

**Comment by ctag-fh-kiel** [comment]
Are you using FW release 0.9?
Can you connect a USB cable to the monitor and start a terminal to capture any error messages on boot/reboot?

**Comment by Synthwall** [comment]
Yes, software v0.9 I'm not familiar with ESP32, can you explain how to do it under Windows 10?

**Comment by ctag-fh-kiel** [comment]
You could use [Putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) to connect through USB serial to the ESP.

**Comment by Synthwall** [comment]
how to set up the program correctly?
![image](https://user-images.githubusercontent.com/102356241/160342022-6cec290c-85b4-492d-8a12-0aa26552c862.png)

**Comment by Synthwall** [comment]
https://youtu.be/lpRoRWvhGiA

**Comment by ctag-fh-kiel** [comment]
Check in windows device manager if the CP2102 USB to serial bridge is
recognized. Then use that COM port in Putty, set the baud rate to 115200
baud and connect. Then you should see error messages from the ESP.

**Comment by Synthwall** [comment]
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4
load:0x3fff0034,len:7316
load:0x40078000,len:14252
load:0x40080400,len:4688
entry 0x400806a4
I (28) boot: ESP-IDF v4.1.2-95-gaeb66e1057 2nd stage bootloader
I (29) boot: compile time 09:31:00
I (29) boot: chip revision: 1
I (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (40) qio_mode: Enabling default flash chip QIO
I (45) boot.esp32: SPI Speed      : 80MHz
I (50) boot.esp32: SPI Mode       : QIO
I (54) boot.esp32: SPI Flash Size : 4MB
I (59) boot: Enabling RNG early entropy source...
I (64) boot: Partition Table:
I (68) boot: ## Label            Usage          Type ST Offset   Length
I (75) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (82) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (90) boot:  2 factory          factory app      00 00 00010000 00200000
I (97) boot: End of partition table
I (102) boot_comm: chip revision: 1, min. application chip revision: 0
I (109) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x2f0f0 (19                                                                                                                                                             2752) map
I (182) esp_image: segment 1: paddr=0x0003f118 vaddr=0x3ffb0000 size=0x00f00 (                                                                                                                                                               3840) load
I (183) esp_image: segment 2: paddr=0x00040020 vaddr=0x400d0020 size=0xc7854 (81                                                                                                                                                             7236) map
I (459) esp_image: segment 3: paddr=0x0010787c vaddr=0x3ffb0f00 size=0x05628 ( 2                                                                                                                                                             2056) load
I (467) esp_image: segment 4: paddr=0x0010ceac vaddr=0x40080000 size=0x00404 (                                                                                                                                                               1028) load
I (468) esp_image: segment 5: paddr=0x0010d2b8 vaddr=0x40080404 size=0x1e134 (12                                                                                                                                                             3188) load
I (540) boot: Loaded app from partition at offset 0x10000
I (540) boot: Disabling RNG early entropy source...
I (541) psram: This chip is ESP32-D0WD
I (545) spiram: Found 64MBit SPI RAM device
I (550) spiram: SPI RAM mode: flash 80m sram 80m
I (555) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (562) cpu_start: Pro cpu up.
I (566) cpu_start: Application information:
I (571) cpu_start: Project name:     ctag-straempler
I (576) cpu_start: App version:      v0.9
I (581) cpu_start: Compile time:     Sep 11 2021 09:54:10
I (587) cpu_start: ELF file SHA256:  32bab0cc5eb6c006...
I (593) cpu_start: ESP-IDF:          v4.1.2-95-gaeb66e1057
I (599) cpu_start: Starting app cpu, entry point is 0x40081720
I (0) cpu_start: App cpu up.
I (1082) spiram: SPI SRAM memory test OK
I (1082) heap_init: Initializing. RAM available for dynamic allocation:
I (1082) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1089) heap_init: At 3FFBEEB0 len 00021150 (132 KiB): DRAM
I (1095) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1101) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1108) heap_init: At 4009E538 len 00001AC8 (6 KiB): IRAM
I (1114) cpu_start: Pro cpu start user code
I (1119) spiram: Adding pool of 4096K of external SPI memory to heap allocator
I (1139) spi_flash: detected chip: gd
I (1139) spi_flash: flash io: qio
W (1139) spi_flash: Detected size(16384k) larger than the size in the binary ima                                                                                                                                                             ge header(4096k). Using the size in the binary image header.
I (1151) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1161) SD: Initializing SD card
I (1161) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulld                                                                                                                                                             own: 0| Intr:0
W (1211) vfs_fat_sdmmc: failed to mount card (13)
E (1211) SD: Failed to mount filesystem. If you want the card to be formatted, s                                                                                                                                                             et format_if_mount_failed = true.
SPI: display device added to spi bus (1)
SPI: attached display device, speed=8000000
SPI: bus uses native pins: false
SPI: display init...
OK
SPI: Max rd speed = 1000000
SPI: Changed speed to 26666666
I (2671) gpio: GPIO[33]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulld                                                                                                                                                             own: 0| Intr:2
I (2671) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulld                                                                                                                                                             own: 0| Intr:2
I (2681) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulld                                                                                                                                                             own: 0| Intr:2
I (2691) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulld                                                                                                                                                             own: 0| Intr:0
I (2701) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulld                                                                                                                                                             own: 0| Intr:0
I (2711) AUDIO: Starting audio task
I (2711) I2S: DMA Malloc info, datalen=blocksize=256, dma_buf_count=4
I (2721) I2S: DMA Malloc info, datalen=blocksize=256, dma_buf_count=4
I (2741) I2S: APLL: Req RATE: 44100, real rate: 44099.988, BITS: 32, CLKM: 1, BC                                                                                                                                                             K_M: 8, MCLK: 22579194.000, SCLK: 2822399.250000, diva: 1, divb: 0
E (2751) FILEIO: Could not open file /sdcard/CONFIG.JSN for reading
E (2751) AUDIO: Couldn't open config.jsn
E (2761) FILEIO: Could not open file /sdcard/CONFIG.JSN for reading
E (2761) FILEIO: Could not open file /sdcard/banks/DEFAULT.JSN for reading
E (2771) PRESET: Root is NULL
E (2781) MENU: Error loading bank from file
E (2781) MENU: Error loading bank
E (2781) FILEIO: Could not open file /sdcard/CONFIG.JSN for reading
E (2791) MENU: Error loading tz_shift from config
I (2951) wifi:wifi driver task: 3ffdd77c, prio:23, stack:6656, core=0
I (2951) system_api: Base MAC address is not set, read default base MAC address                                                                                                                                                              from BLK0 of EFUSE
I (2951) system_api: Base MAC address is not set, read default base MAC address                                                                                                                                                              from BLK0 of EFUSE
I (2971) wifi:wifi firmware version: 1424aca
I (2971) wifi:config NVS flash: enabled
I (2971) wifi:config nano formating: disabled
I (2971) wifi:Init data frame dynamic rx buffer num: 32
I (2981) wifi:Init management frame dynamic rx buffer num: 32
I (2981) wifi:Init management short buffer num: 32
I (2991) wifi:Init static tx buffer num: 16
I (2991) wifi:Init static rx buffer size: 1600
I (3001) wifi:Init static rx buffer num: 10
I (3001) wifi:Init dynamic rx buffer num: 32
I (3011) wifi_init: rx ba win: 16
I (3011) wifi_init: tcpip mbox: 32
I (3011) wifi_init: udp mbox: 6
I (3021) wifi_init: tcp mbox: 6
I (3021) wifi_init: tcp tx win: 5744
I (3021) wifi_init: tcp rx win: 5744
I (3031) wifi_init: tcp mss: 1440
I (3031) wifi_init: WiFi/LWIP prefer SPIRAM
I (3041) wifi_init: WiFi IRAM OP enabled
I (3041) wifi_init: WiFi RX IRAM OP enabled
E (3051) FILEIO: Could not open file /sdcard/CONFIG.JSN for reading
E (3051) FILEIO: root == NULL
I (3061) WIFI: Setting WiFi configuration SSID ▒?
I (3061) phy_init: phy_version 4660,0162888,Dec 23 2020
I (3161) wifi:mode : sta (a8:48:fa:5a:a6:c4)

**Comment by Synthwall** [comment]
Brilliant! Working! Thanks bro!)

**Comment by ctag-fh-kiel** [comment]
Perfect, have fun :)
