### ISSUE TITLE
Cannot access freesounds.org

### ISSUE THREAD

**Issue by deepiain** [ctag-fh-kiel/ctag-straempler#27]
I have built and flashed the unit OK, it goes online, (the time updates) but when i go to slots/slot 1/freesounds.org nothing happens. I have checked the setup file and the api key matches my key on freesounds. not sure what to try now?

**Comment by ctag-fh-kiel** [comment]
You have to download the files from Freesound first. See e.g. this video:
https://youtu.be/zmj8tKPHV8g?si=JyRLGDA9_HxLYXsa
sample->id enter the freesound sound id here and Strämpler will download the file from Freesound
This sound e.g. has the id 714254:
https://freesound.org/people/strangehorizon/sounds/714254/

Once the file has been downloaded, it is stored on your local SD-card, then you can access it with slots->freesound

**Comment by deepiain** [comment]
AAAAH! it lives :) thank you so much

**Comment by deepiain** [comment]
resolved
