### ISSUE TITLE
accessing via URL

### ISSUE THREAD

**Issue by deepiain** [ctag-fh-kiel/ctag-straempler#28]
I am having issues using http://ctag-modular/ to access to transfer sounds. I have tried a few different browsers. The module is in the right mode (as per the youtube video) but when I enter the URL i get a "server not found" on the browser.

**Comment by ctag-fh-kiel** [comment]
Have you tried using the direct IP address? Maybe MDNS is not allowed in your network.

**Comment by deepiain** [comment]
The IP address instead of URL worked (but not in Chrome, only in Safari) - thank you
