### ISSUE TITLE
Where to buy it ?

### ISSUE THREAD

**Issue by 0mars** [ctag-fh-kiel/ctag-straempler#8]
everylink on modulargrid is dead, the project is open source, but are there any builds available or kits ?

**Comment by lechmaof** [comment]
I ordered the panels and pcbs from JLCpcb, 5 sets for about 45 euros total, incl shipping (czech republic), tax etc. Still haven't ordered the parts to actually build it though.

**Comment by 0mars** [comment]
@lechmaof very interesting project. I want a full kit or fully assembled if possible.

**Comment by 0mars** [comment]
keep me posted!

**Comment by ctag-fh-kiel** [comment]
We don't sell kits or assembled modules, however, there may be some builders out there who could do it for you. All design files are open source cc-sa-by-nc license (non-commercial where we are totally fine if someone builds a few of them and sells them, just not on a larger e.g. >10).

**Comment by 0mars** [comment]
can u sell at least pcb and panel ?

Best,
Omar

**Comment by ctag-fh-kiel** [comment]
Hi Omar, it's easy to order e.g. from jlcpcb.com, just drag and drop these files in the quotation menu: 
https://github.com/ctag-fh-kiel/esp32-eurorack-audio/blob/rev-d/Gerber/Gerber.rar (PCB, 4-layers)
https://github.com/ctag-fh-kiel/esp32-eurorack-audio/blob/rev-d/GerberFrontplate/GerberFrontplate.rar (Front Plate, choose your own color)

For building it, here is the bill of materials (BOM):
https://github.com/ctag-fh-kiel/esp32-eurorack-audio/blob/rev-d/ESP32-Eurorack-Audio-BOM-RevD.xlsx

Let me know if you have problems...

**Comment by 0mars** [comment]
ok thanks
